import React, { useMemo } from 'react';
import { Language, User, UserProgress, PracticeMode } from '../types';
import { MicrophoneIcon, HeadphonesIcon, TargetIcon, CardsIcon, BookOpenIcon, RoleplayIcon, WritingIcon, SparklesIcon, CameraIcon } from './icons';

interface PracticeHubPageProps {
    language: Language;
    progress: UserProgress | null;
    user: User | null;
    onStartPractice: (mode: PracticeMode) => void;
}

interface PracticeCardProps {
    title: string;
    description: string;
    icon: React.ElementType;
    color: string;
    count?: number;
    onClick: () => void;
    disabled?: boolean;
}

const PracticeCard: React.FC<PracticeCardProps> = ({ title, description, icon: Icon, color, count, onClick, disabled = false }) => {
    
    return (
        <button
            onClick={onClick}
            disabled={disabled}
            className={`relative p-6 rounded-2xl text-left transition-all duration-300 transform hover:-translate-y-1 w-full overflow-hidden ${disabled ? 'bg-slate-100 dark:bg-slate-800 cursor-not-allowed' : 'bg-white dark:bg-slate-800 shadow-lg hover:shadow-xl'}`}
        >
            {disabled && <div className="absolute inset-0 bg-slate-200/50 dark:bg-slate-900/50 z-10"></div>}
            
            <div className="relative z-0">
                <div className={`p-3 rounded-lg inline-block mb-4 ${color}`}>
                    <Icon className="w-8 h-8 text-white" />
                </div>
                <h3 className={`text-xl font-bold ${disabled ? 'text-slate-400 dark:text-slate-500' : 'text-slate-800 dark:text-white'}`}>{title}</h3>
                <p className="text-slate-500 dark:text-slate-400 mb-4">{description}</p>
                {count !== undefined && (
                    <span className="font-bold text-sm text-slate-600 dark:text-slate-300 bg-slate-200 dark:bg-slate-700 px-3 py-1 rounded-full">
                        {count} item{count !== 1 ? 's' : ''} to review
                    </span>
                )}
                 {disabled && count === 0 && (
                     <span className="font-bold text-sm text-slate-500 dark:text-slate-400">
                        Nothing to practice yet!
                    </span>
                 )}
            </div>
        </button>
    );
};


const PracticeHubPage: React.FC<PracticeHubPageProps> = ({ language, progress, user, onStartPractice }) => {
    const mistakeCount = progress?.mistakes?.length ?? 0;
    
    const vocabularyToReviewCount = useMemo(() => {
        if (!progress?.learnedVocabulary) return 0;
        const now = new Date();
        return progress.learnedVocabulary.filter(item => {
            if (!item.nextReview) return false;
            const reviewDate = new Date(item.nextReview);
            return reviewDate <= now;
        }).length;
    }, [progress]);


    const practiceOptions: Omit<PracticeCardProps, 'onClick'>[] = [
        {
            title: 'Vision Practice',
            description: 'Describe images and get AI feedback.',
            icon: CameraIcon,
            color: 'bg-amber-500',
        },
        {
            title: 'Live Conversation',
            description: 'Speak directly with an AI tutor in real-time.',
            icon: MicrophoneIcon,
            color: 'bg-teal-500',
        },
        {
            title: 'Role-play Scenarios',
            description: 'Practice real-world conversations.',
            icon: RoleplayIcon,
            color: 'bg-orange-500',
        },
        {
            title: 'Writing Workshop',
            description: 'Hone your writing skills with AI-graded prompts.',
            icon: WritingIcon,
            color: 'bg-indigo-500',
        },
        {
            title: 'Pronunciation',
            description: 'Get AI feedback on your pronunciation.',
            icon: MicrophoneIcon,
            color: 'bg-blue-500',
        },
        {
            title: 'Listening',
            description: 'Boost your listening with audio-only sessions.',
            icon: HeadphonesIcon,
            color: 'bg-violet-500',
        },
        {
            title: 'Your Mistakes',
            description: 'Practice the concepts you\'ve struggled with.',
            icon: TargetIcon,
            color: 'bg-rose-500',
            count: mistakeCount,
            disabled: mistakeCount === 0,
        },
        {
            title: 'Smart Review',
            description: 'Review words with our Spaced Repetition System.',
            icon: CardsIcon,
            color: 'bg-amber-500',
            count: vocabularyToReviewCount,
            disabled: vocabularyToReviewCount === 0,
        },
        {
            title: 'Stories',
            description: 'Jump into an interactive story generated by AI.',
            icon: BookOpenIcon,
            color: 'bg-emerald-500',
        },
    ];

    const modeMap: Record<string, PracticeMode> = {
        'Vision Practice': 'vision',
        'Live Conversation': 'conversation',
        'Listening': 'listening',
        'Your Mistakes': 'mistakes',
        'Smart Review': 'vocabulary',
        'Stories': 'stories',
        'Pronunciation': 'pronunciation',
        'Role-play Scenarios': 'roleplay',
        'Writing Workshop': 'writing',
    };

    return (
        <div className="px-4 animate-fade-in">
            <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100 mb-2">Practice Hub</h2>
            <p className="text-slate-500 dark:text-slate-400 mb-10">Sharpen your {language.name} skills!</p>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {practiceOptions.map(opt => (
                    <PracticeCard
                        key={opt.title}
                        {...opt}
                        onClick={() => onStartPractice(modeMap[opt.title])}
                    />
                ))}
            </div>
        </div>
    );
};

export default PracticeHubPage;