import React, { useMemo } from 'react';
import { Language, User, UserProgress, PracticeMode, Page } from '../types';
import { MicrophoneIcon, HeadphonesIcon, TargetIcon, CardsIcon, BookOpenIcon, RoleplayIcon, WritingIcon } from './icons';

interface PracticeHubPageProps {
    language: Language;
    progress: UserProgress | null;
    user: User | null;
    onStartPractice: (mode: PracticeMode) => void;
    onNavigate: (page: Page) => void;
}

interface PracticeCardProps {
    title: string;
    description: string;
    icon: React.ElementType;
    color: string;
    count?: number;
    onClick: () => void;
    disabled?: boolean;
}

const PracticeCard: React.FC<PracticeCardProps> = ({ title, description, icon: Icon, color, count, onClick, disabled = false }) => {
    
    return (
        <div className="relative group">
             <div className={`absolute -inset-0.5 bg-gradient-to-r from-sky-600 to-teal-600 rounded-2xl blur opacity-0 group-hover:opacity-75 transition duration-300 ${disabled ? 'hidden' : ''}`}></div>
            <button
                onClick={onClick}
                disabled={disabled}
                className={`relative p-6 rounded-2xl text-left transition-all duration-300 w-full overflow-hidden h-full ${disabled ? 'bg-slate-800/50 cursor-not-allowed' : 'bg-slate-800/80 backdrop-blur-sm shadow-lg group-hover:bg-slate-900'}`}
            >
                {disabled && <div className="absolute inset-0 bg-slate-900/50 z-10"></div>}
                
                <div className="relative z-0">
                    <div className={`p-3 rounded-lg inline-block mb-4 ${color} shadow-lg`}>
                        <Icon className="w-8 h-8 text-white" />
                    </div>
                    <h3 className={`text-xl font-bold ${disabled ? 'text-slate-500' : 'text-white'}`}>{title}</h3>
                    <p className="text-slate-400 mb-4">{description}</p>
                    {count !== undefined && (
                        <span className="font-bold text-sm text-slate-300 bg-slate-700 px-3 py-1 rounded-full">
                            {count} item{count !== 1 ? 's' : ''} to review
                        </span>
                    )}
                     {disabled && count === 0 && (
                         <span className="font-bold text-sm text-slate-400">
                            Nothing to practice yet!
                        </span>
                     )}
                </div>
            </button>
        </div>
    );
};


const PracticeHubPage: React.FC<PracticeHubPageProps> = ({ language, progress, user, onStartPractice, onNavigate }) => {
    const mistakeCount = progress?.mistakes?.length ?? 0;
    
    const vocabularyToReviewCount = useMemo(() => {
        if (!progress?.learnedVocabulary) return 0;
        const now = new Date();
        return progress.learnedVocabulary.filter(item => {
            if (!item.nextReview) return false;
            const reviewDate = new Date(item.nextReview);
            return reviewDate <= now;
        }).length;
    }, [progress]);


    const practiceOptions: Omit<PracticeCardProps, 'onClick'>[] = [
        {
            title: 'Live Conversation',
            description: 'Speak directly with an AI tutor in real-time.',
            icon: MicrophoneIcon,
            color: 'bg-teal-500',
        },
        {
            title: 'Role-play Scenarios',
            description: 'Practice real-world conversations.',
            icon: RoleplayIcon,
            color: 'bg-orange-500',
        },
        {
            title: 'Writing Workshop',
            description: 'Hone your writing skills with AI-graded prompts.',
            icon: WritingIcon,
            color: 'bg-indigo-500',
        },
        {
            title: 'Flashcard Decks',
            description: 'Create and study your own custom flashcards.',
            icon: CardsIcon,
            color: 'bg-cyan-500',
        },
        {
            title: 'Pronunciation',
            description: 'Get AI feedback on your pronunciation.',
            icon: MicrophoneIcon,
            color: 'bg-blue-500',
        },
        {
            title: 'Listening',
            description: 'Boost your listening with audio-only sessions.',
            icon: HeadphonesIcon,
            color: 'bg-violet-500',
        },
        {
            title: 'Your Mistakes',
            description: 'Practice the concepts you\'ve struggled with.',
            icon: TargetIcon,
            color: 'bg-rose-500',
            count: mistakeCount,
            disabled: mistakeCount === 0,
        },
        {
            title: 'Smart Review',
            description: 'Review words with our Spaced Repetition System.',
            icon: CardsIcon,
            color: 'bg-amber-500',
            count: vocabularyToReviewCount,
            disabled: vocabularyToReviewCount === 0,
        },
        {
            title: 'Stories',
            description: 'Jump into an interactive story generated by AI.',
            icon: BookOpenIcon,
            color: 'bg-emerald-500',
        },
    ];

    const modeMap: Record<string, PracticeMode> = {
        'Live Conversation': 'conversation',
        'Listening': 'listening',
        'Your Mistakes': 'mistakes',
        'Smart Review': 'vocabulary',
        'Stories': 'stories',
        'Pronunciation': 'pronunciation',
        'Role-play Scenarios': 'roleplay',
        'Writing Workshop': 'writing',
    };

    return (
        <div className="px-4 animate-fade-in">
            <h2 className="text-3xl font-bold text-slate-100 mb-2">Practice Hub</h2>
            <p className="text-slate-400 mb-10">Sharpen your {language.name} skills!</p>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {practiceOptions.map(opt => (
                    <PracticeCard
                        key={opt.title}
                        {...opt}
                        onClick={() => {
                            if (opt.title === 'Flashcard Decks') {
                                onNavigate(Page.FlashcardDecks);
                            } else {
                                onStartPractice(modeMap[opt.title]);
                            }
                        }}
                    />
                ))}
            </div>
        </div>
    );
};

export default PracticeHubPage;